//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDiagram")]

namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	/// <summary>
	/// DomainClass JCJAPGDRCDERAWebBDDiagram
	/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDiagram.DisplayName", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDiagram.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("7d6d74a5-3b0b-4a63-979e-d8a56874e4c5")]
	public partial class JCJAPGDRCDERAWebBDDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEnt)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntShape newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRel)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRelShape newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRelShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionRango)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionRangoShape newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionRangoShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionEnum)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionEnumShape newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionEnumShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPagina)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPaginaShape newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPaginaShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloCampo)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloCampoShape newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloCampoShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPortal)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.estiloPortlShape newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.estiloPortlShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadShape newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.Relacion)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionShape newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionReferencesEntidad)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEntidadRelacion newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEntidadRelacion(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadHasAtributoEnt)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.ConectorAtibuto newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.ConectorAtibuto(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionHasAtributoRel)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.ConectorAtibuto newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.ConectorAtibuto(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntHasRestriccion)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorRestricciones newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorRestricciones(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntHasEstiloCampo)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEstiloCampo newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEstiloCampo(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRelHasEstiloCampo)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEstiloCampo newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEstiloCampo(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadHasEstiloPagina)
			{
				global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEstiloPagina newShape = new global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEstiloPagina(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadShape.DecoratorsInitialized += EntidadShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionShape.DecoratorsInitialized += RelacionShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntShape.DecoratorsInitialized += AtributoEntShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionRangoShape.DecoratorsInitialized += RestriccionRangoShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionEnumShape.DecoratorsInitialized += RestriccionEnumShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPaginaShape.DecoratorsInitialized += EstiloPaginaShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloCampoShape.DecoratorsInitialized += EstiloCampoShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JCJAPGDRCDERAWebBD.estiloPortlShape.DecoratorsInitialized += estiloPortlShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEntidadRelacion.DecoratorsInitialized += ConnectorEntidadRelacionDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EntidadShape.
		/// </summary>
		internal static partial class EntidadShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EntidadShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for RelacionShape.
		/// </summary>
		internal static partial class RelacionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for RelacionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.Relacion.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AtributoEntShape.
		/// </summary>
		internal static partial class AtributoEntShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AtributoEntShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEnt.keyAtrDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "KeyIconDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.Atributo.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for RestriccionRangoShape.
		/// </summary>
		internal static partial class RestriccionRangoShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for RestriccionRangoShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionRango.CalculadoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "RangoDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for RestriccionEnumShape.
		/// </summary>
		internal static partial class RestriccionEnumShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for RestriccionEnumShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionEnum.ValoresDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "EnumDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EstiloPaginaShape.
		/// </summary>
		internal static partial class EstiloPaginaShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EstiloPaginaShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.Estilos.CalculadoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "propertiesDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EstiloCampoShape.
		/// </summary>
		internal static partial class EstiloCampoShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EstiloCampoShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.Estilos.CalculadoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "propertiesDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for estiloPortlShape.
		/// </summary>
		internal static partial class estiloPortlShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for estiloPortlShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.Estilos.CalculadoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TextDecorator1").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ConnectorEntidadRelacion.
		/// </summary>
		internal static partial class ConnectorEntidadRelacionDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ConnectorEntidadRelacion.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionReferencesEntidad.cardinalidadDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.JCJAPGDRCDERAWebBD.ConectarRelacionEntidadConnectAction conectarRelacionEntidadConnectAction;
		private global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntidadToolConnectAction atributoEntidadToolConnectAction;
		private global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRelacionToolConnectAction atributoRelacionToolConnectAction;
		private global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadEstiloPaginaToolConnectAction entidadEstiloPaginaToolConnectAction;
		private global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntEstiloCampoConnectAction atributoEntEstiloCampoConnectAction;
		private global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntRestriccionConnectAction atributoEntRestriccionConnectAction;
		private global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRelEstiloCampoConnectAction atributoRelEstiloCampoConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDToolboxHelper.ConectarRelacionEntidadFilterString))
				{
					if (this.conectarRelacionEntidadConnectAction == null)
					{
						this.conectarRelacionEntidadConnectAction = new global::UPM_IPS.JCJAPGDRCDERAWebBD.ConectarRelacionEntidadConnectAction(this);
						this.conectarRelacionEntidadConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.conectarRelacionEntidadConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDToolboxHelper.AtributoEntidadToolFilterString))
				{
					if (this.atributoEntidadToolConnectAction == null)
					{
						this.atributoEntidadToolConnectAction = new global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntidadToolConnectAction(this);
						this.atributoEntidadToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.atributoEntidadToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDToolboxHelper.AtributoRelacionToolFilterString))
				{
					if (this.atributoRelacionToolConnectAction == null)
					{
						this.atributoRelacionToolConnectAction = new global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRelacionToolConnectAction(this);
						this.atributoRelacionToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.atributoRelacionToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDToolboxHelper.EntidadEstiloPaginaToolFilterString))
				{
					if (this.entidadEstiloPaginaToolConnectAction == null)
					{
						this.entidadEstiloPaginaToolConnectAction = new global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadEstiloPaginaToolConnectAction(this);
						this.entidadEstiloPaginaToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.entidadEstiloPaginaToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDToolboxHelper.AtributoEntEstiloCampoFilterString))
				{
					if (this.atributoEntEstiloCampoConnectAction == null)
					{
						this.atributoEntEstiloCampoConnectAction = new global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntEstiloCampoConnectAction(this);
						this.atributoEntEstiloCampoConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.atributoEntEstiloCampoConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDToolboxHelper.AtributoEntRestriccionFilterString))
				{
					if (this.atributoEntRestriccionConnectAction == null)
					{
						this.atributoEntRestriccionConnectAction = new global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntRestriccionConnectAction(this);
						this.atributoEntRestriccionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.atributoEntRestriccionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDToolboxHelper.AtributoRelEstiloCampoFilterString))
				{
					if (this.atributoRelEstiloCampoConnectAction == null)
					{
						this.atributoRelEstiloCampoConnectAction = new global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRelEstiloCampoConnectAction(this);
						this.atributoRelEstiloCampoConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.atributoRelEstiloCampoConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.conectarRelacionEntidadConnectAction != null)
					{
						this.conectarRelacionEntidadConnectAction.Dispose();
						this.conectarRelacionEntidadConnectAction = null;
					}
					if(this.atributoEntidadToolConnectAction != null)
					{
						this.atributoEntidadToolConnectAction.Dispose();
						this.atributoEntidadToolConnectAction = null;
					}
					if(this.atributoRelacionToolConnectAction != null)
					{
						this.atributoRelacionToolConnectAction.Dispose();
						this.atributoRelacionToolConnectAction = null;
					}
					if(this.entidadEstiloPaginaToolConnectAction != null)
					{
						this.entidadEstiloPaginaToolConnectAction.Dispose();
						this.entidadEstiloPaginaToolConnectAction = null;
					}
					if(this.atributoEntEstiloCampoConnectAction != null)
					{
						this.atributoEntEstiloCampoConnectAction.Dispose();
						this.atributoEntEstiloCampoConnectAction = null;
					}
					if(this.atributoEntRestriccionConnectAction != null)
					{
						this.atributoEntRestriccionConnectAction.Dispose();
						this.atributoEntRestriccionConnectAction = null;
					}
					if(this.atributoRelEstiloCampoConnectAction != null)
					{
						this.atributoRelEstiloCampoConnectAction.Dispose();
						this.atributoRelEstiloCampoConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// JCJAPGDRCDERAWebBDDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x7d6d74a5, 0x3b0b, 0x4a63, 0x97, 0x9e, 0xd8, 0xa5, 0x68, 0x74, 0xe4, 0xc5);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public JCJAPGDRCDERAWebBDDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public JCJAPGDRCDERAWebBDDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEnt), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionRango), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionEnum), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPagina), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloCampo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPortal), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.Relacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionReferencesEntidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadHasAtributoEnt), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionHasAtributoRel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntHasRestriccion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntHasEstiloCampo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRelHasEstiloCampo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadHasEstiloPagina), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEnt)
				{
					parentElement = GetParentForAtributoEnt((global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEnt)childElement);
				} else
				if(childElement is global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRel)
				{
					parentElement = GetParentForAtributoRel((global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRel)childElement);
				} else
				if(childElement is global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionRango)
				{
					parentElement = GetParentForRestriccionRango((global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionRango)childElement);
				} else
				if(childElement is global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionEnum)
				{
					parentElement = GetParentForRestriccionEnum((global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionEnum)childElement);
				} else
				if(childElement is global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPagina)
				{
					parentElement = GetParentForEstiloPagina((global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPagina)childElement);
				} else
				if(childElement is global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloCampo)
				{
					parentElement = GetParentForEstiloCampo((global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloCampo)childElement);
				} else
				if(childElement is global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPortal)
				{
					parentElement = GetParentForEstiloPortal((global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPortal)childElement);
				} else
				if(childElement is global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad)
				{
					parentElement = GetParentForEntidad((global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad)childElement);
				} else
				if(childElement is global::UPM_IPS.JCJAPGDRCDERAWebBD.Relacion)
				{
					parentElement = GetParentForRelacion((global::UPM_IPS.JCJAPGDRCDERAWebBD.Relacion)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel GetParentForEntidad( global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel result = root.DERAWebBDModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel GetParentForRelacion( global::UPM_IPS.JCJAPGDRCDERAWebBD.Relacion root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel result = root.DERAWebBDModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel GetParentForAtributoEnt( global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEnt root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad root2 = root.Entidad;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel result = root2.DERAWebBDModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel GetParentForAtributoRel( global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRel root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JCJAPGDRCDERAWebBD.Relacion root2 = root.Relacion;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel result = root2.DERAWebBDModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel GetParentForRestriccionRango( global::UPM_IPS.JCJAPGDRCDERAWebBD.Restriccion root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEnt root2 = root.AtributoEnt;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad root4 = root2.Entidad;
				if ( root4 == null ) return null;
				// Segments 4 and 5
				global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel result = root4.DERAWebBDModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel GetParentForRestriccionEnum( global::UPM_IPS.JCJAPGDRCDERAWebBD.Restriccion root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEnt root2 = root.AtributoEnt;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad root4 = root2.Entidad;
				if ( root4 == null ) return null;
				// Segments 4 and 5
				global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel result = root4.DERAWebBDModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel GetParentForEstiloPagina( global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPagina root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad root2 = root.Entidad;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel result = root2.DERAWebBDModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel GetParentForEstiloCampo( global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloCampo root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEnt root2 = root.AtributoEnt;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JCJAPGDRCDERAWebBD.Entidad root4 = root2.Entidad;
				if ( root4 == null ) return null;
				// Segments 4 and 5
				global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel result = root4.DERAWebBDModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel GetParentForEstiloPortal( global::UPM_IPS.JCJAPGDRCDERAWebBD.EstiloPortal root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModel result = root.DERAWebBDModel;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionReferencesEntidad), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionReferencesEntidad.cardinalidadDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorEntidadRelacion.FindConnectorEntidadRelacionDecorator("NameDecorator");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionReferencesEntidad.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionReferencesEntidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadHasAtributoEnt), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.RelacionHasAtributoRel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntHasRestriccion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoEntHasEstiloCampo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoRelHasEstiloCampo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadHasEstiloPagina), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDiagram diagram = linkShape.Diagram as global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
