//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	/// <summary>
	/// DomainModel JCJAPGDRCDERAWebBDDomainModel
	/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBD
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel.DisplayName", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("e88bbe60-548e-495c-a1d9-2502188490ac")]
	public partial class JCJAPGDRCDERAWebBDDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// JCJAPGDRCDERAWebBDDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xe88bbe60, 0x548e, 0x495c, 0xa1, 0xd9, 0x25, 0x02, 0x18, 0x84, 0x90, 0xac);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public JCJAPGDRCDERAWebBDDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(DERAWebBDModel),
				typeof(Entidad),
				typeof(Relacion),
				typeof(EstiloPortal),
				typeof(EstiloPagina),
				typeof(Estilos),
				typeof(Atributo),
				typeof(AtributoClave),
				typeof(EstiloCampo),
				typeof(Restriccion),
				typeof(RestriccionRango),
				typeof(RestriccionEnum),
				typeof(ValorEnumerado),
				typeof(DERAWebBDModelHasEntidades),
				typeof(DERAWebBDModelHasRelaciones),
				typeof(DERAWebBDModelHasEstiloPortal),
				typeof(EntidadHasEstiloPagina),
				typeof(RelacionReferencesEntidad),
				typeof(DERAWebBDModelHasAtributo),
				typeof(DERAWebBDModelHasAtributoClave),
				typeof(EntidadReferencesAtributo),
				typeof(EntidadReferencesAtributoClave),
				typeof(RelacionReferencesAtributo),
				typeof(AtributoHasEstiloCampo),
				typeof(AtributoClaveHasEstiloCampo),
				typeof(RestriccionEnumHasValorEnumerado),
				typeof(AtributoHasRestriccion),
				typeof(JCJAPGDRCDERAWebBDDiagram),
				typeof(ConectaAtributo),
				typeof(EntidadRelacionConnector),
				typeof(ConectaEstiloPagina),
				typeof(ConectaEstiloCampo),
				typeof(ConectaAtributoRestriccion),
				typeof(EntidadShape),
				typeof(RestriccionRangoShape),
				typeof(ValoresEnumShape),
				typeof(EstiloCampoShape),
				typeof(EstiloPaginaShape),
				typeof(EstiloPortalShape),
				typeof(AtributoShape),
				typeof(AtrClaveShape),
				typeof(RestriccionEnumShape),
				typeof(RelacionShape),
				typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.FixUpDiagram),
				typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorRolePlayerChanged),
				typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemAddRule),
				typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemDeleteRule),
				typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemRolePlayerChangeRule),
				typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Entidad), "Name", Entidad.NameDomainPropertyId, typeof(Entidad.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "Name", Relacion.NameDomainPropertyId, typeof(Relacion.NamePropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortal), "TextoTitulo", EstiloPortal.TextoTituloDomainPropertyId, typeof(EstiloPortal.TextoTituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortal), "ColorFondo", EstiloPortal.ColorFondoDomainPropertyId, typeof(EstiloPortal.ColorFondoPropertyHandler)),
				new DomainMemberInfo(typeof(Estilos), "Color", Estilos.ColorDomainPropertyId, typeof(Estilos.ColorPropertyHandler)),
				new DomainMemberInfo(typeof(Estilos), "Tamanio", Estilos.TamanioDomainPropertyId, typeof(Estilos.TamanioPropertyHandler)),
				new DomainMemberInfo(typeof(Estilos), "Fuente", Estilos.FuenteDomainPropertyId, typeof(Estilos.FuentePropertyHandler)),
				new DomainMemberInfo(typeof(Estilos), "Alineacion", Estilos.AlineacionDomainPropertyId, typeof(Estilos.AlineacionPropertyHandler)),
				new DomainMemberInfo(typeof(Estilos), "Calculado", Estilos.CalculadoDomainPropertyId, typeof(Estilos.CalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Name", Atributo.NameDomainPropertyId, typeof(Atributo.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "TipoDato", Atributo.TipoDatoDomainPropertyId, typeof(Atributo.TipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Longitud", Atributo.LongitudDomainPropertyId, typeof(Atributo.LongitudPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoClave), "Name", AtributoClave.NameDomainPropertyId, typeof(AtributoClave.NamePropertyHandler)),
				new DomainMemberInfo(typeof(EstiloCampo), "TipoCampo", EstiloCampo.TipoCampoDomainPropertyId, typeof(EstiloCampo.TipoCampoPropertyHandler)),
				new DomainMemberInfo(typeof(RestriccionRango), "Minimo", RestriccionRango.MinimoDomainPropertyId, typeof(RestriccionRango.MinimoPropertyHandler)),
				new DomainMemberInfo(typeof(RestriccionRango), "Maximo", RestriccionRango.MaximoDomainPropertyId, typeof(RestriccionRango.MaximoPropertyHandler)),
				new DomainMemberInfo(typeof(RestriccionRango), "Calculado", RestriccionRango.CalculadoDomainPropertyId, typeof(RestriccionRango.CalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(RestriccionEnum), "NombreEnumerado", RestriccionEnum.NombreEnumeradoDomainPropertyId, typeof(RestriccionEnum.NombreEnumeradoPropertyHandler)),
				new DomainMemberInfo(typeof(ValorEnumerado), "Nombre", ValorEnumerado.NombreDomainPropertyId, typeof(ValorEnumerado.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(RelacionReferencesEntidad), "cardinalidad", RelacionReferencesEntidad.cardinalidadDomainPropertyId, typeof(RelacionReferencesEntidad.cardinalidadPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasEntidades), "DERAWebBDModel", DERAWebBDModelHasEntidades.DERAWebBDModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasEntidades), "Entidad", DERAWebBDModelHasEntidades.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasRelaciones), "DERAWebBDModel", DERAWebBDModelHasRelaciones.DERAWebBDModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasRelaciones), "Relacion", DERAWebBDModelHasRelaciones.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasEstiloPortal), "DERAWebBDModel", DERAWebBDModelHasEstiloPortal.DERAWebBDModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasEstiloPortal), "EstiloPortal", DERAWebBDModelHasEstiloPortal.EstiloPortalDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasEstiloPagina), "Entidad", EntidadHasEstiloPagina.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasEstiloPagina), "EstiloPagina", EntidadHasEstiloPagina.EstiloPaginaDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesEntidad), "Relacion", RelacionReferencesEntidad.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesEntidad), "Entidad", RelacionReferencesEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasAtributo), "DERAWebBDModel", DERAWebBDModelHasAtributo.DERAWebBDModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasAtributo), "Atributo", DERAWebBDModelHasAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasAtributoClave), "DERAWebBDModel", DERAWebBDModelHasAtributoClave.DERAWebBDModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DERAWebBDModelHasAtributoClave), "AtributoClave", DERAWebBDModelHasAtributoClave.AtributoClaveDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesAtributo), "Entidad", EntidadReferencesAtributo.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesAtributo), "Atributo", EntidadReferencesAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesAtributoClave), "Entidad", EntidadReferencesAtributoClave.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesAtributoClave), "AtributoClave", EntidadReferencesAtributoClave.AtributoClaveDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesAtributo), "Relacion", RelacionReferencesAtributo.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesAtributo), "Atributo", RelacionReferencesAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoHasEstiloCampo), "Atributo", AtributoHasEstiloCampo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoHasEstiloCampo), "EstiloCampo", AtributoHasEstiloCampo.EstiloCampoDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoClaveHasEstiloCampo), "AtributoClave", AtributoClaveHasEstiloCampo.AtributoClaveDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoClaveHasEstiloCampo), "EstiloCampo", AtributoClaveHasEstiloCampo.EstiloCampoDomainRoleId),
				new DomainRolePlayerInfo(typeof(RestriccionEnumHasValorEnumerado), "RestriccionEnum", RestriccionEnumHasValorEnumerado.RestriccionEnumDomainRoleId),
				new DomainRolePlayerInfo(typeof(RestriccionEnumHasValorEnumerado), "ValorEnumerado", RestriccionEnumHasValorEnumerado.ValorEnumeradoDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoHasRestriccion), "Atributo", AtributoHasRestriccion.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoHasRestriccion), "Restriccion", AtributoHasRestriccion.RestriccionDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(29);
				createElementMap.Add(typeof(DERAWebBDModel), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(Relacion), 2);
				createElementMap.Add(typeof(EstiloPortal), 3);
				createElementMap.Add(typeof(EstiloPagina), 4);
				createElementMap.Add(typeof(Atributo), 5);
				createElementMap.Add(typeof(AtributoClave), 6);
				createElementMap.Add(typeof(EstiloCampo), 7);
				createElementMap.Add(typeof(RestriccionRango), 8);
				createElementMap.Add(typeof(RestriccionEnum), 9);
				createElementMap.Add(typeof(ValorEnumerado), 10);
				createElementMap.Add(typeof(JCJAPGDRCDERAWebBDDiagram), 11);
				createElementMap.Add(typeof(ConectaAtributo), 12);
				createElementMap.Add(typeof(EntidadRelacionConnector), 13);
				createElementMap.Add(typeof(ConectaEstiloPagina), 14);
				createElementMap.Add(typeof(ConectaEstiloCampo), 15);
				createElementMap.Add(typeof(ConectaAtributoRestriccion), 16);
				createElementMap.Add(typeof(EntidadShape), 17);
				createElementMap.Add(typeof(RestriccionRangoShape), 18);
				createElementMap.Add(typeof(ValoresEnumShape), 19);
				createElementMap.Add(typeof(EstiloCampoShape), 20);
				createElementMap.Add(typeof(EstiloPaginaShape), 21);
				createElementMap.Add(typeof(EstiloPortalShape), 22);
				createElementMap.Add(typeof(AtributoShape), 23);
				createElementMap.Add(typeof(AtrClaveShape), 24);
				createElementMap.Add(typeof(RestriccionEnumShape), 25);
				createElementMap.Add(typeof(RelacionShape), 26);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new DERAWebBDModel(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new Relacion(partition, propertyAssignments);
				case 3: return new EstiloPortal(partition, propertyAssignments);
				case 4: return new EstiloPagina(partition, propertyAssignments);
				case 5: return new Atributo(partition, propertyAssignments);
				case 6: return new AtributoClave(partition, propertyAssignments);
				case 7: return new EstiloCampo(partition, propertyAssignments);
				case 8: return new RestriccionRango(partition, propertyAssignments);
				case 9: return new RestriccionEnum(partition, propertyAssignments);
				case 10: return new ValorEnumerado(partition, propertyAssignments);
				case 11: return new JCJAPGDRCDERAWebBDDiagram(partition, propertyAssignments);
				case 12: return new ConectaAtributo(partition, propertyAssignments);
				case 13: return new EntidadRelacionConnector(partition, propertyAssignments);
				case 14: return new ConectaEstiloPagina(partition, propertyAssignments);
				case 15: return new ConectaEstiloCampo(partition, propertyAssignments);
				case 16: return new ConectaAtributoRestriccion(partition, propertyAssignments);
				case 17: return new EntidadShape(partition, propertyAssignments);
				case 18: return new RestriccionRangoShape(partition, propertyAssignments);
				case 19: return new ValoresEnumShape(partition, propertyAssignments);
				case 20: return new EstiloCampoShape(partition, propertyAssignments);
				case 21: return new EstiloPaginaShape(partition, propertyAssignments);
				case 22: return new EstiloPortalShape(partition, propertyAssignments);
				case 23: return new AtributoShape(partition, propertyAssignments);
				case 24: return new AtrClaveShape(partition, propertyAssignments);
				case 25: return new RestriccionEnumShape(partition, propertyAssignments);
				case 26: return new RelacionShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(14);
				createElementLinkMap.Add(typeof(DERAWebBDModelHasEntidades), 0);
				createElementLinkMap.Add(typeof(DERAWebBDModelHasRelaciones), 1);
				createElementLinkMap.Add(typeof(DERAWebBDModelHasEstiloPortal), 2);
				createElementLinkMap.Add(typeof(EntidadHasEstiloPagina), 3);
				createElementLinkMap.Add(typeof(RelacionReferencesEntidad), 4);
				createElementLinkMap.Add(typeof(DERAWebBDModelHasAtributo), 5);
				createElementLinkMap.Add(typeof(DERAWebBDModelHasAtributoClave), 6);
				createElementLinkMap.Add(typeof(EntidadReferencesAtributo), 7);
				createElementLinkMap.Add(typeof(EntidadReferencesAtributoClave), 8);
				createElementLinkMap.Add(typeof(RelacionReferencesAtributo), 9);
				createElementLinkMap.Add(typeof(AtributoHasEstiloCampo), 10);
				createElementLinkMap.Add(typeof(AtributoClaveHasEstiloCampo), 11);
				createElementLinkMap.Add(typeof(RestriccionEnumHasValorEnumerado), 12);
				createElementLinkMap.Add(typeof(AtributoHasRestriccion), 13);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new DERAWebBDModelHasEntidades(partition, roleAssignments, propertyAssignments);
				case 1: return new DERAWebBDModelHasRelaciones(partition, roleAssignments, propertyAssignments);
				case 2: return new DERAWebBDModelHasEstiloPortal(partition, roleAssignments, propertyAssignments);
				case 3: return new EntidadHasEstiloPagina(partition, roleAssignments, propertyAssignments);
				case 4: return new RelacionReferencesEntidad(partition, roleAssignments, propertyAssignments);
				case 5: return new DERAWebBDModelHasAtributo(partition, roleAssignments, propertyAssignments);
				case 6: return new DERAWebBDModelHasAtributoClave(partition, roleAssignments, propertyAssignments);
				case 7: return new EntidadReferencesAtributo(partition, roleAssignments, propertyAssignments);
				case 8: return new EntidadReferencesAtributoClave(partition, roleAssignments, propertyAssignments);
				case 9: return new RelacionReferencesAtributo(partition, roleAssignments, propertyAssignments);
				case 10: return new AtributoHasEstiloCampo(partition, roleAssignments, propertyAssignments);
				case 11: return new AtributoClaveHasEstiloCampo(partition, roleAssignments, propertyAssignments);
				case 12: return new RestriccionEnumHasValorEnumerado(partition, roleAssignments, propertyAssignments);
				case 13: return new AtributoHasRestriccion(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return JCJAPGDRCDERAWebBDDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (JCJAPGDRCDERAWebBDDomainModel.resourceManager == null)
				{
					JCJAPGDRCDERAWebBDDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(JCJAPGDRCDERAWebBDDomainModel).Assembly);
				}
				return JCJAPGDRCDERAWebBDDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return JCJAPGDRCDERAWebBDDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return JCJAPGDRCDERAWebBDDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (JCJAPGDRCDERAWebBDDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new JCJAPGDRCDERAWebBDCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					JCJAPGDRCDERAWebBDDomainModel.copyClosure = copyFilter;
				}
				return JCJAPGDRCDERAWebBDDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (JCJAPGDRCDERAWebBDDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new JCJAPGDRCDERAWebBDDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					JCJAPGDRCDERAWebBDDomainModel.removeClosure = removeFilter;
				}
				return JCJAPGDRCDERAWebBDDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JCJAPGDRCDERAWebBDDeleteClosure : JCJAPGDRCDERAWebBDDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JCJAPGDRCDERAWebBDDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JCJAPGDRCDERAWebBDDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public JCJAPGDRCDERAWebBDDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModelHasEntidades.EntidadDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModelHasRelaciones.RelacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModelHasEstiloPortal.EstiloPortalDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.EntidadHasEstiloPagina.EstiloPaginaDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModelHasAtributo.AtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.DERAWebBDModelHasAtributoClave.AtributoClaveDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoHasEstiloCampo.EstiloCampoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoClaveHasEstiloCampo.EstiloCampoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.RestriccionEnumHasValorEnumerado.ValorEnumeradoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JCJAPGDRCDERAWebBD.AtributoHasRestriccion.RestriccionDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JCJAPGDRCDERAWebBDCopyClosure : JCJAPGDRCDERAWebBDCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JCJAPGDRCDERAWebBDCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JCJAPGDRCDERAWebBDCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JCJAPGDRCDERAWebBDCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	/// <summary>
	/// DomainEnumeration: TipoDato
	/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TipoDato
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoDato
	{
		/// <summary>
		/// Entero
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TipoDato.Entero
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.TipoDato/Entero.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Entero = 1,
		/// <summary>
		/// Real
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TipoDato.Real
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.TipoDato/Real.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Real = 3,
		/// <summary>
		/// Alfanumerico
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TipoDato.Alfanumerico
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.TipoDato/Alfanumerico.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Alfanumerico = 0,
		/// <summary>
		/// Fecha
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TipoDato.Fecha
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.TipoDato/Fecha.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Fecha = 2,
	}
}
namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	/// <summary>
	/// DomainEnumeration: TiposCampo
	/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TiposCampo
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TiposCampo
	{
		/// <summary>
		/// AreaTexto
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TiposCampo.AreaTexto
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.TiposCampo/AreaTexto.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		AreaTexto = 0,
		/// <summary>
		/// Check
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TiposCampo.Check
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.TiposCampo/Check.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Check = 1,
		/// <summary>
		/// Boton
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TiposCampo.Boton
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.TiposCampo/Boton.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Boton = 2,
		/// <summary>
		/// ListaDesple
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.TiposCampo.ListaDesple
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.TiposCampo/ListaDesple.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		ListaDesple = 3,
	}
}
namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	/// <summary>
	/// DomainEnumeration: Alineacion
	/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.Alineacion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Alineacion
	{
		/// <summary>
		/// Center
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.Alineacion.Center
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.Alineacion/Center.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Center = 0,
		/// <summary>
		/// Izquierda
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.Alineacion.Izquierda
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.Alineacion/Izquierda.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Izquierda = 1,
		/// <summary>
		/// Derecha
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.Alineacion.Derecha
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.Alineacion/Derecha.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Derecha = 2,
	}
}
namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	/// <summary>
	/// DomainEnumeration: MaxCardinalidad
	/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.MaxCardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum MaxCardinalidad
	{
		/// <summary>
		/// Uno
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.MaxCardinalidad.Uno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.MaxCardinalidad/Uno.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Uno = 0,
		/// <summary>
		/// N
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.MaxCardinalidad.N
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.MaxCardinalidad/N.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		N = 1,
	}
}
namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	/// <summary>
	/// DomainEnumeration: MinCardinalidad
	/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.MinCardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum MinCardinalidad
	{
		/// <summary>
		/// Cero
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.MinCardinalidad.Cero
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.MinCardinalidad/Cero.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Cero = 0,
		/// <summary>
		/// Uno
		/// Description for UPM_IPS.JCJAPGDRCDERAWebBD.MinCardinalidad.Uno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JCJAPGDRCDERAWebBD.MinCardinalidad/Uno.Description", typeof(global::UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel), "UPM_IPS.JCJAPGDRCDERAWebBD.GeneratedCode.DomainModelResx")]
		Uno = 1,
	}
}

