<?xml version="1.0" encoding="utf-8"?>
<xsd:schema id="JCJAPGDRCDERAWebBDSchema" targetNamespace="http://schemas.microsoft.com/dsltools/JCJAPGDRCDERAWebBD" elementFormDefault="qualified" xmlns="http://schemas.microsoft.com/dsltools/JCJAPGDRCDERAWebBD" xmlns:core="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:import id="CoreSchema" namespace="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" />
  <!-- DERAWebBDModel -->
  <xsd:element name="dERAWebBDModel" type="DERAWebBDModel" substitutionGroup="core:modelElement" />
  <xsd:complexType name="DERAWebBDModel">
    <xsd:annotation>
      <xsd:documentation>The root in which all other elements are embedded. Appears as a diagram.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Relationship: DERAWebBDModelHasEntidades -->
          <xsd:element name="entidades" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instances of DERAWebBDModelHasEntidades</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="dERAWebBDModelHasEntidades" minOccurs="0" maxOccurs="unbounded">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of DERAWebBDModelHasEntidades needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <!-- Relationship: DERAWebBDModelHasRelaciones -->
          <xsd:element name="relaciones" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instances of DERAWebBDModelHasRelaciones</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="dERAWebBDModelHasRelaciones" minOccurs="0" maxOccurs="unbounded">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of DERAWebBDModelHasRelaciones needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <!-- Relationship: DERAWebBDModelHasEstiloPortal -->
          <xsd:element name="estiloPortal" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instances of DERAWebBDModelHasEstiloPortal</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="dERAWebBDModelHasEstiloPortal" minOccurs="0" maxOccurs="unbounded">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of DERAWebBDModelHasEstiloPortal needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- dslVersion -->
        <xsd:attribute name="dslVersion" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Version of the model serialized in this file.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: Name -->
        <xsd:attribute name="name" type="xsd:string" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- DERAWebBDModel Moniker -->
  <xsd:element name="dERAWebBDModelMoniker" type="DERAWebBDModelMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="DERAWebBDModelMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for DERAWebBDModel instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Entidad -->
  <xsd:element name="entidad" type="Entidad" substitutionGroup="core:modelElement" />
  <xsd:complexType name="Entidad">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Relationship: EntidadHasEstiloPagina -->
          <xsd:element name="estiloPagina" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instance of EntidadHasEstiloPagina</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="entidadHasEstiloPagina" minOccurs="0" maxOccurs="1">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of EntidadHasEstiloPagina needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <!-- Relationship: EntidadHasAtributoEnt -->
          <xsd:element name="atributoEnt" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instances of EntidadHasAtributoEnt</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="entidadHasAtributoEnt" minOccurs="0" maxOccurs="unbounded">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of EntidadHasAtributoEnt needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: Name -->
        <xsd:attribute name="name" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Entidad Moniker -->
  <xsd:element name="entidadMoniker" type="EntidadMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="EntidadMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for Entidad instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="name" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Relacion -->
  <xsd:element name="relacion" type="Relacion" substitutionGroup="core:modelElement" />
  <xsd:complexType name="Relacion">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Relationship: RelacionReferencesEntidad -->
          <xsd:element name="entidad" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instances of RelacionReferencesEntidad</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="relacionReferencesEntidad" minOccurs="0" maxOccurs="unbounded">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of RelacionReferencesEntidad needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <!-- Relationship: RelacionHasAtributoRel -->
          <xsd:element name="atributoRel" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instances of RelacionHasAtributoRel</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="relacionHasAtributoRel" minOccurs="0" maxOccurs="unbounded">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of RelacionHasAtributoRel needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: Name -->
        <xsd:attribute name="name" type="xsd:string" use="required" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Relacion Moniker -->
  <xsd:element name="relacionMoniker" type="RelacionMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="RelacionMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for Relacion instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="name" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EstiloPortal -->
  <xsd:element name="estiloPortal" type="EstiloPortal" substitutionGroup="estilos" />
  <xsd:complexType name="EstiloPortal">
    <xsd:complexContent>
      <xsd:extension base="Estilos">
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: TextoTitulo -->
        <xsd:attribute name="textoTitulo" type="xsd:string" />
        <!-- Property: ColorFondo -->
        <xsd:attribute name="colorFondo" type="xsd:string" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EstiloPortal Moniker -->
  <xsd:element name="estiloPortalMoniker" type="EstiloPortalMoniker" substitutionGroup="estilosMoniker" />
  <xsd:complexType name="EstiloPortalMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for EstiloPortal instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="EstilosMoniker">
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EstiloPagina -->
  <xsd:element name="estiloPagina" type="EstiloPagina" substitutionGroup="estilos" />
  <xsd:complexType name="EstiloPagina">
    <xsd:complexContent>
      <xsd:extension base="Estilos">
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EstiloPagina Moniker -->
  <xsd:element name="estiloPaginaMoniker" type="EstiloPaginaMoniker" substitutionGroup="estilosMoniker" />
  <xsd:complexType name="EstiloPaginaMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for EstiloPagina instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="EstilosMoniker">
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Estilos -->
  <xsd:element name="estilos" abstract="true" type="Estilos" substitutionGroup="core:modelElement" />
  <xsd:complexType name="Estilos" abstract="true" >
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: Color -->
        <xsd:attribute name="color" type="xsd:string" />
        <!-- Property: Tamanio -->
        <xsd:attribute name="tamanio" type="xsd:string" />
        <!-- Property: Fuente -->
        <xsd:attribute name="fuente" type="xsd:string" />
        <!-- Property: Alineacion -->
        <xsd:attribute name="alineacion" type="Alineacion" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Estilos Moniker -->
  <xsd:element name="estilosMoniker" abstract="true" type="EstilosMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="EstilosMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for Estilos instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Atributo -->
  <xsd:element name="atributo" type="Atributo" substitutionGroup="core:modelElement" />
  <xsd:complexType name="Atributo">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: Name -->
        <xsd:attribute name="name" type="xsd:string" />
        <!-- Property: TipoDato -->
        <xsd:attribute name="tipoDato" type="TipoDato" />
        <!-- Property: Longitud -->
        <xsd:attribute name="longitud" type="xsd:string" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Atributo Moniker -->
  <xsd:element name="atributoMoniker" type="AtributoMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="AtributoMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for Atributo instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EstiloCampo -->
  <xsd:element name="estiloCampo" type="EstiloCampo" substitutionGroup="estilos" />
  <xsd:complexType name="EstiloCampo">
    <xsd:complexContent>
      <xsd:extension base="Estilos">
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: TipoCampo -->
        <xsd:attribute name="tipoCampo" type="TiposCampo" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EstiloCampo Moniker -->
  <xsd:element name="estiloCampoMoniker" type="EstiloCampoMoniker" substitutionGroup="estilosMoniker" />
  <xsd:complexType name="EstiloCampoMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for EstiloCampo instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="EstilosMoniker">
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Restriccion -->
  <xsd:element name="restriccion" abstract="true" type="Restriccion" substitutionGroup="core:modelElement" />
  <xsd:complexType name="Restriccion" abstract="true" >
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Restriccion Moniker -->
  <xsd:element name="restriccionMoniker" abstract="true" type="RestriccionMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="RestriccionMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for Restriccion instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- RestriccionRango -->
  <xsd:element name="restriccionRango" type="RestriccionRango" substitutionGroup="restriccion" />
  <xsd:complexType name="RestriccionRango">
    <xsd:complexContent>
      <xsd:extension base="Restriccion">
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: Minimo -->
        <xsd:attribute name="minimo" type="xsd:string" />
        <!-- Property: Maximo -->
        <xsd:attribute name="maximo" type="xsd:string" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- RestriccionRango Moniker -->
  <xsd:element name="restriccionRangoMoniker" type="RestriccionRangoMoniker" substitutionGroup="restriccionMoniker" />
  <xsd:complexType name="RestriccionRangoMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for RestriccionRango instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="RestriccionMoniker">
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- RestriccionEnum -->
  <xsd:element name="restriccionEnum" type="RestriccionEnum" substitutionGroup="restriccion" />
  <xsd:complexType name="RestriccionEnum">
    <xsd:complexContent>
      <xsd:extension base="Restriccion">
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: Valores -->
        <xsd:attribute name="valores" type="xsd:string" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- RestriccionEnum Moniker -->
  <xsd:element name="restriccionEnumMoniker" type="RestriccionEnumMoniker" substitutionGroup="restriccionMoniker" />
  <xsd:complexType name="RestriccionEnumMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for RestriccionEnum instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="RestriccionMoniker">
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoEnt -->
  <xsd:element name="atributoEnt" type="AtributoEnt" substitutionGroup="atributo" />
  <xsd:complexType name="AtributoEnt">
    <xsd:complexContent>
      <xsd:extension base="Atributo">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Relationship: AtributoEntHasRestriccion -->
          <xsd:element name="restriccion" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instance of AtributoEntHasRestriccion</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="atributoEntHasRestriccion" minOccurs="0" maxOccurs="1">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of AtributoEntHasRestriccion needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <!-- Relationship: AtributoEntHasEstiloCampo -->
          <xsd:element name="estiloCampo" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instances of AtributoEntHasEstiloCampo</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="atributoEntHasEstiloCampo" minOccurs="0" maxOccurs="unbounded">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of AtributoEntHasEstiloCampo needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: keyAtr -->
        <xsd:attribute name="keyAtr" type="xsd:boolean" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoEnt Moniker -->
  <xsd:element name="atributoEntMoniker" type="AtributoEntMoniker" substitutionGroup="atributoMoniker" />
  <xsd:complexType name="AtributoEntMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for AtributoEnt instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="AtributoMoniker">
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoRel -->
  <xsd:element name="atributoRel" type="AtributoRel" substitutionGroup="atributo" />
  <xsd:complexType name="AtributoRel">
    <xsd:complexContent>
      <xsd:extension base="Atributo">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Relationship: AtributoRelHasRestriccion -->
          <xsd:element name="restriccion" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instance of AtributoRelHasRestriccion</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="atributoRelHasRestriccion" minOccurs="0" maxOccurs="1">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of AtributoRelHasRestriccion needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <!-- Relationship: AtributoRelHasEstiloCampo -->
          <xsd:element name="estiloCampo" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>Instances of AtributoRelHasEstiloCampo</xsd:documentation>
            </xsd:annotation>
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="atributoRelHasEstiloCampo" minOccurs="0" maxOccurs="unbounded">
                  <xsd:annotation>
                    <xsd:documentation>[Instance of AtributoRelHasEstiloCampo needs to be serialized in full-form]</xsd:documentation>
                  </xsd:annotation>
                </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoRel Moniker -->
  <xsd:element name="atributoRelMoniker" type="AtributoRelMoniker" substitutionGroup="atributoMoniker" />
  <xsd:complexType name="AtributoRelMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for AtributoRel instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="AtributoMoniker">
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- DERAWebBDModelHasEntidades -->
  <xsd:element name="dERAWebBDModelHasEntidades" type="DERAWebBDModelHasEntidades" substitutionGroup="core:modelElement" />
  <xsd:complexType name="DERAWebBDModelHasEntidades">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end Entidad -->
          <xsd:element ref="entidad" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- DERAWebBDModelHasEntidades Moniker -->
  <xsd:element name="dERAWebBDModelHasEntidadesMoniker" type="DERAWebBDModelHasEntidadesMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="DERAWebBDModelHasEntidadesMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for DERAWebBDModelHasEntidades instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- DERAWebBDModelHasRelaciones -->
  <xsd:element name="dERAWebBDModelHasRelaciones" type="DERAWebBDModelHasRelaciones" substitutionGroup="core:modelElement" />
  <xsd:complexType name="DERAWebBDModelHasRelaciones">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end Relacion -->
          <xsd:element ref="relacion" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- DERAWebBDModelHasRelaciones Moniker -->
  <xsd:element name="dERAWebBDModelHasRelacionesMoniker" type="DERAWebBDModelHasRelacionesMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="DERAWebBDModelHasRelacionesMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for DERAWebBDModelHasRelaciones instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EntidadHasEstiloPagina -->
  <xsd:element name="entidadHasEstiloPagina" type="EntidadHasEstiloPagina" substitutionGroup="core:modelElement" />
  <xsd:complexType name="EntidadHasEstiloPagina">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end EstiloPagina -->
          <xsd:element ref="estiloPagina" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EntidadHasEstiloPagina Moniker -->
  <xsd:element name="entidadHasEstiloPaginaMoniker" type="EntidadHasEstiloPaginaMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="EntidadHasEstiloPaginaMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for EntidadHasEstiloPagina instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- RelacionReferencesEntidad -->
  <xsd:element name="relacionReferencesEntidad" type="RelacionReferencesEntidad" substitutionGroup="core:modelElement" />
  <xsd:complexType name="RelacionReferencesEntidad">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end Entidad -->
          <xsd:element ref="entidadMoniker" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
        <!-- Property: cardinalidad -->
        <xsd:attribute name="cardinalidad" type="xsd:string" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- RelacionReferencesEntidad Moniker -->
  <xsd:element name="relacionReferencesEntidadMoniker" type="RelacionReferencesEntidadMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="RelacionReferencesEntidadMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for RelacionReferencesEntidad instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EntidadHasAtributoEnt -->
  <xsd:element name="entidadHasAtributoEnt" type="EntidadHasAtributoEnt" substitutionGroup="core:modelElement" />
  <xsd:complexType name="EntidadHasAtributoEnt">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end AtributoEnt -->
          <xsd:element ref="atributoEnt" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- EntidadHasAtributoEnt Moniker -->
  <xsd:element name="entidadHasAtributoEntMoniker" type="EntidadHasAtributoEntMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="EntidadHasAtributoEntMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for EntidadHasAtributoEnt instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- RelacionHasAtributoRel -->
  <xsd:element name="relacionHasAtributoRel" type="RelacionHasAtributoRel" substitutionGroup="core:modelElement" />
  <xsd:complexType name="RelacionHasAtributoRel">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end AtributoRel -->
          <xsd:element ref="atributoRel" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- RelacionHasAtributoRel Moniker -->
  <xsd:element name="relacionHasAtributoRelMoniker" type="RelacionHasAtributoRelMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="RelacionHasAtributoRelMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for RelacionHasAtributoRel instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoEntHasRestriccion -->
  <xsd:element name="atributoEntHasRestriccion" type="AtributoEntHasRestriccion" substitutionGroup="core:modelElement" />
  <xsd:complexType name="AtributoEntHasRestriccion">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end Restriccion -->
          <xsd:element ref="restriccion" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoEntHasRestriccion Moniker -->
  <xsd:element name="atributoEntHasRestriccionMoniker" type="AtributoEntHasRestriccionMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="AtributoEntHasRestriccionMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for AtributoEntHasRestriccion instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoEntHasEstiloCampo -->
  <xsd:element name="atributoEntHasEstiloCampo" type="AtributoEntHasEstiloCampo" substitutionGroup="core:modelElement" />
  <xsd:complexType name="AtributoEntHasEstiloCampo">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end EstiloCampo -->
          <xsd:element ref="estiloCampo" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoEntHasEstiloCampo Moniker -->
  <xsd:element name="atributoEntHasEstiloCampoMoniker" type="AtributoEntHasEstiloCampoMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="AtributoEntHasEstiloCampoMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for AtributoEntHasEstiloCampo instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoRelHasRestriccion -->
  <xsd:element name="atributoRelHasRestriccion" type="AtributoRelHasRestriccion" substitutionGroup="core:modelElement" />
  <xsd:complexType name="AtributoRelHasRestriccion">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end Restriccion -->
          <xsd:element ref="restriccion" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoRelHasRestriccion Moniker -->
  <xsd:element name="atributoRelHasRestriccionMoniker" type="AtributoRelHasRestriccionMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="AtributoRelHasRestriccionMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for AtributoRelHasRestriccion instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoRelHasEstiloCampo -->
  <xsd:element name="atributoRelHasEstiloCampo" type="AtributoRelHasEstiloCampo" substitutionGroup="core:modelElement" />
  <xsd:complexType name="AtributoRelHasEstiloCampo">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end EstiloCampo -->
          <xsd:element ref="estiloCampo" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- AtributoRelHasEstiloCampo Moniker -->
  <xsd:element name="atributoRelHasEstiloCampoMoniker" type="AtributoRelHasEstiloCampoMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="AtributoRelHasEstiloCampoMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for AtributoRelHasEstiloCampo instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- DERAWebBDModelHasEstiloPortal -->
  <xsd:element name="dERAWebBDModelHasEstiloPortal" type="DERAWebBDModelHasEstiloPortal" substitutionGroup="core:modelElement" />
  <xsd:complexType name="DERAWebBDModelHasEstiloPortal">
    <xsd:complexContent>
      <xsd:extension base="core:ModelElement">
        <xsd:sequence minOccurs="0" maxOccurs="1">
          <!-- Target end EstiloPortal -->
          <xsd:element ref="estiloPortal" minOccurs="1" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>[Target role-player]</xsd:documentation>
            </xsd:annotation>
          </xsd:element>
        </xsd:sequence>
        <!-- Id -->
        <xsd:attribute name="Id" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>Instance Guid of this element, needed because SerializeId is set to true.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- DERAWebBDModelHasEstiloPortal Moniker -->
  <xsd:element name="dERAWebBDModelHasEstiloPortalMoniker" type="DERAWebBDModelHasEstiloPortalMoniker" substitutionGroup="core:modelElementMoniker" />
  <xsd:complexType name="DERAWebBDModelHasEstiloPortalMoniker">
    <xsd:annotation>
      <xsd:documentation>Moniker for DERAWebBDModelHasEstiloPortal instance.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="core:ModelElementMoniker">
        <xsd:attribute name="Id" type="xsd:string" >
          <xsd:annotation>
            <xsd:documentation>Attribute to store the moniker string.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!-- Enum TipoDato -->
  <xsd:simpleType name="TipoDato">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Entero"/>
      <xsd:enumeration value="Real"/>
      <xsd:enumeration value="Alfanumerico"/>
      <xsd:enumeration value="Fecha"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <!-- Enum TiposCampo -->
  <xsd:simpleType name="TiposCampo">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="AreaTexto"/>
      <xsd:enumeration value="Check"/>
      <xsd:enumeration value="Boton"/>
      <xsd:enumeration value="ListaDesple"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <!-- Enum Alineacion -->
  <xsd:simpleType name="Alineacion">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Center"/>
      <xsd:enumeration value="Izquierda"/>
      <xsd:enumeration value="Derecha"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <!-- Enum MaxCardinalidad -->
  <xsd:simpleType name="MaxCardinalidad">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Uno"/>
      <xsd:enumeration value="N"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <!-- Enum MinCardinalidad -->
  <xsd:simpleType name="MinCardinalidad">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Cero"/>
      <xsd:enumeration value="Uno"/>
    </xsd:restriction>
  </xsd:simpleType>
  
</xsd:schema>

