//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class DERAWebBDModel
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateDERAWebBDModelMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.EstiloPortal == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"DERAWebBDModel", "", "EstiloPortal"),
						"DSL0001", this);
			}
		} // ValidateDERAWebBDModelMultiplicity
	} // class DERAWebBDModel
} // UPM_IPS.JCJAPGDRCDERAWebBD

namespace UPM_IPS.JCJAPGDRCDERAWebBD
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class RestriccionEnum
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateRestriccionEnumMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.ValorEnumerado.Count == 0)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.JCJAPGDRCDERAWebBD.JCJAPGDRCDERAWebBDDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"RestriccionEnum", "", "ValorEnumerado"),
						"DSL0001", this);
			}
		} // ValidateRestriccionEnumMultiplicity
	} // class RestriccionEnum
} // UPM_IPS.JCJAPGDRCDERAWebBD

	
 